CONNECT TARGET /
RUN
{
  RECOVER COPY OF DATABASE 
    WITH TAG 'xe_incr';
  BACKUP 
    INCREMENTAL LEVEL 1
    FOR RECOVER OF COPY WITH TAG 'xe_incr'
    DATABASE;
}
DELETE NOPROMPT OBSOLETE;
LIST BACKUP;
EXIT;
